version: '3.8'

services:
  rstudio:
    build: .
    image: rstudio-server:latest
    container_name: rstudio
    ports:
      - "8787:8787"
    environment:
      PASSWORD: rstudio # Set your password
      USER: rstudio     # Username for RStudio
    volumes:
      - ./data:/home/rstudio # Bind a volume for persistent data
    restart: unless-stopped
